#!/bin/env sh

gen(){

    filename=$(basename "$1")
    extension="${filename##*.}"
    filename="${filename%.*}"
 
    echo "compiling file and running valgrind tool...";
    v icrun $1;
    PID=`cat $filename.icc_val_out | awk '{print $1 }' | head -1 | sed "s/=//g"`
    echo "File compiled. Trace generated. Process Id: $PID";
    echo "Parsing the valgrind trace now...";
    pv $filename.icc_val_out  gleipnir.$PID macpo > macpo.out.$PID
    echo "Parsed the trace.";
    echo "Converting to a format macpo-analyze can understand";
    val-to-macpo macpo.out.$PID vmacpo.out
    echo "Generated vmacpo.out";
    echo "try: macpo-analyze vmacpot.out"
}

clr(){
    v clro;
    rm -rf macpo.out*

}

case $1 in
    clr) clr;;
    gen) gen $2;;
    help ) echo "Usage $0 {|<filename>|gen <filename>|clr}";;
    *) echo "use gen <filename>";;
esac
